# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./TeaFrontend
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173" # Map port 5173 for frontend
#     environment:
#       - REACT_APP_GRAPHQL_ENDPOINT=http://backend:3000/graphql
#     networks:
#       - app-network
#     volumes:
#       - ./TeaFrontend:/app
#       - /app/node_modules

#   backend:
#     build:
#       context: ./TeaBackend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000" # Map port 3000 for backend
#     environment:
#       - NODE_ENV=development
#       - MONGODB_URI=<YOUR_MONGODB_ATLAS_CONNECTION_STRING>
#     networks:
#       - app-network
#     volumes:
#       - ./TeaBackend:/app
#       - /app/node_modules

# networks:
#   app-network:
#     driver: bridge
version: '3.8'

services:
  frontend:
    build:
      context: ./TeaFrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map port 5173 for frontend
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=http://backend:3000/graphql
    networks:
      - app-network
    volumes:
      - ./TeaFrontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./TeaBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 for backend
    environment:
      - NODE_ENV=development
      - MONGODB_URI=<YOUR_MONGODB_ATLAS_CONNECTION_STRING>
    networks:
      - app-network
    volumes:
      - ./TeaBackend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

