version: '3.8'

services:
  frontend:
    image: rchd88/projectsdp:frontend-latest # Ganti build dengan image
    container_name: projectsdp-frontend
    ports:
      - "5173:5173" # Map port 5173 untuk frontend
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=http://backend:3000/graphql
    networks:
      - app-network

  backend:
    image: rchd88/projectsdp:backend-latest # Ganti build dengan image
    container_name: projectsdp-backend
    ports:
      - "3000:3000" # Map port 3000 untuk backend
    environment:
      - NODE_ENV=development
      - MONGODB_URI=<YOUR_MONGODB_ATLAS_CONNECTION_STRING> # Ganti dengan URI MongoDB Anda
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
